In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pit

In [2]:
n = np.eye(6, 6, dtype=int)
n

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [3]:
n = np.array([1,2,3,4,5,6,7,8,9])
n

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
n = np.random.randint(3)
n

2

In [13]:
n = np.random.randint(1,10,(2,3,3))
n

array([[[8, 7, 1],
        [3, 7, 7],
        [3, 5, 8]],

       [[1, 4, 8],
        [6, 9, 4],
        [7, 6, 8]]])

In [22]:
n = np.random.randn(1,2,3)
n

array([[[ 0.66924469,  0.81517607, -0.42408143],
        [ 1.63414687, -0.45304388,  0.99796686]]])

In [25]:
n = np.random.normal(loc = 1,scale = 2,size = (2,3))
n

array([[-0.17939877,  2.74328966,  3.4446438 ],
       [ 0.69827319, -1.95111014, -0.01892457]])

In [28]:
n = np.random.random()
n

0.48217087554532545

In [34]:
m = np.random.random(size = (3,4))
m

array([[0.99006492, 0.40388381, 0.83545048, 0.62430971],
       [0.39560152, 0.20623973, 0.03277905, 0.98631369],
       [0.06273663, 0.14136887, 0.45215112, 0.2230489 ]])

In [36]:
n = np.random.rand(4,5)
n

array([[0.39043935, 0.86481319, 0.49521825, 0.22536483, 0.12666   ],
       [0.06022617, 0.36102062, 0.97021275, 0.28528951, 0.40121994],
       [0.75789383, 0.19092191, 0.71775166, 0.81024561, 0.46210704],
       [0.85312586, 0.48807828, 0.57177332, 0.52848237, 0.20200654]])

In [37]:
n = np.random.randint(0, 256, size=(20,40,3))
n

array([[[255,  93,  93],
        [199,  58,  19],
        [150,  70, 152],
        ...,
        [211, 114, 130],
        [160,  75,  90],
        [102, 113, 187]],

       [[236,  32, 125],
        [ 87,  51,  55],
        [171, 207, 143],
        ...,
        [165, 222, 166],
        [109, 204, 223],
        [  3, 235,  59]],

       [[249, 141, 145],
        [116,  31,  13],
        [168, 243, 245],
        ...,
        [165, 208,  97],
        [145, 205, 213],
        [120, 218, 138]],

       ...,

       [[ 66, 177,  85],
        [207, 175, 167],
        [ 87,  75,  25],
        ...,
        [110, 116, 107],
        [153, 253, 111],
        [ 88,   6,  25]],

       [[250,  47, 207],
        [ 48, 214, 174],
        [182,  40, 206],
        ...,
        [201, 232, 235],
        [ 15, 223,  66],
        [ 13, 138, 154]],

       [[  9,  77,  39],
        [169, 223,  32],
        [ 42, 110, 186],
        ...,
        [125, 161,  49],
        [ 73, 117, 208],
        [108, 208, 215]]

In [40]:
n = np.random.randint(1,10,size = (4,5))
n

array([[1, 2, 4, 5, 1],
       [3, 5, 8, 2, 3],
       [9, 8, 6, 1, 4],
       [3, 9, 5, 1, 6]])

In [42]:
a = np.array(n)
a

array([[1, 2, 4, 5, 1],
       [3, 5, 8, 2, 3],
       [9, 8, 6, 1, 4],
       [3, 9, 5, 1, 6]])

In [46]:
a[2][3]

1

In [52]:
n = np.zeros((5,5),dtype=int)
n

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [56]:
n[[0,3,-1]] = 2
n

array([[2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [58]:
n = np.random.randint(0,100,size = (5,6))
n

array([[12, 68, 28, 29, 80, 39],
       [ 4, 17, 72, 82, 49, 78],
       [74, 10, 51, 45, 11, 25],
       [80, 82, 27, 47, 35, 60],
       [18, 49, 84, 31, 68, 92]])

In [60]:
n[::-1]

array([[18, 49, 84, 31, 68, 92],
       [80, 82, 27, 47, 35, 60],
       [74, 10, 51, 45, 11, 25],
       [ 4, 17, 72, 82, 49, 78],
       [12, 68, 28, 29, 80, 39]])

In [63]:
n[:,::-1]

array([[39, 80, 29, 28, 68, 12],
       [78, 49, 82, 72, 17,  4],
       [25, 11, 45, 51, 10, 74],
       [60, 35, 47, 27, 82, 80],
       [92, 68, 31, 84, 49, 18]])

In [64]:
n[::-1,::-1]

array([[92, 68, 31, 84, 49, 18],
       [60, 35, 47, 27, 82, 80],
       [25, 11, 45, 51, 10, 74],
       [78, 49, 82, 72, 17,  4],
       [39, 80, 29, 28, 68, 12]])

In [7]:
n = np.random.randint(0,100,size=(3,4))
n

array([[45, 90, 46, 61],
       [ 9, 39, 95, 84],
       [81, 39, 50, 73]])

In [9]:
n.T

array([[45,  9, 81],
       [90, 39, 39],
       [46, 95, 50],
       [61, 84, 73]])

In [14]:
n = np.random.randint(0,100,size=(3,4,5))
n

array([[[75, 55, 13, 75, 96],
        [ 6, 51, 82, 66, 37],
        [86, 14, 82, 59, 73],
        [28, 85, 54, 37, 52]],

       [[17, 75, 76, 32, 82],
        [58, 50,  6, 24, 79],
        [19, 78,  7, 82, 56],
        [51, 19, 83, 28, 37]],

       [[26, 89, 22, 42, 85],
        [18, 87, 62, 29, 97],
        [79, 81, 79, 33, 77],
        [19, 90,  4, 32, 47]]])

In [19]:
np.transpose(n,axes=(2,0,1))

array([[[75,  6, 86, 28],
        [17, 58, 19, 51],
        [26, 18, 79, 19]],

       [[55, 51, 14, 85],
        [75, 50, 78, 19],
        [89, 87, 81, 90]],

       [[13, 82, 82, 54],
        [76,  6,  7, 83],
        [22, 62, 79,  4]],

       [[75, 66, 59, 37],
        [32, 24, 82, 28],
        [42, 29, 33, 32]],

       [[96, 37, 73, 52],
        [82, 79, 56, 37],
        [85, 97, 77, 47]]])

In [22]:
n = np.random.randint(0,100,size=(4,5))
n

array([[36, 85, 94, 97, 73],
       [60, 40, 79, 19, 52],
       [69, 26, 60, 92, 78],
       [35, 94,  1, 57, 62]])

In [24]:
np.sum(n,axis=0)

array([200, 245, 234, 265, 265])

In [25]:
np.sum(n,axis=1)

array([385, 250, 325, 249])

In [26]:
np.max(n)

97

In [27]:
np.min(n)

1

In [28]:
np.mean(n)

60.45

In [29]:
np.average(n)

60.45

In [30]:
np.median(n)

61.0

In [38]:
n = n.reshape(-1)
display(n)

array([36, 85, 94, 97, 73, 60, 40, 79, 19, 52, 69, 26, 60, 92, 78, 35, 94,
        1, 57, 62])

In [39]:
np.argmin(n)

17

In [40]:
np.argmax(n)

3

In [41]:
np.std(n)

26.69920410798794

In [43]:
np.var(n)

712.8475

In [44]:
np.power(n,2)

array([1296, 7225, 8836, 9409, 5329, 3600, 1600, 6241,  361, 2704, 4761,
        676, 3600, 8464, 6084, 1225, 8836,    1, 3249, 3844], dtype=int32)

In [51]:
n = np.array([1,2,2,3,3,4,4,555,666,7,7,8,666,8,9],dtype=int)
n

array([  1,   2,   2,   3,   3,   4,   4, 555, 666,   7,   7,   8, 666,
         8,   9])

In [52]:
display(np.argmax(n))

8

In [53]:
np.argwhere(n==np.max(n))

array([[ 8],
       [12]], dtype=int64)

In [59]:
n1 = np.random.randint(0,100,size=(4,5))
n1

array([[ 5, 33, 58,  1, 75],
       [ 2, 39, 52, 72, 29],
       [59, 53, 83, 79, 32],
       [35, 11, 85, 66, 49]])

In [64]:
n2 = np.random.randint(0,100,size=(5,4))
n2

array([[ 3, 32, 22, 28],
       [34, 47, 91, 24],
       [ 7, 59, 71,  8],
       [11, 69, 80, 12],
       [ 0, 99, 80, 51]])

In [61]:
n1+n2

array([[ 45,  83, 100,  56,  82],
       [ 85, 105, 109,  87,  39],
       [147, 106,  91, 115,  45],
       [104,  51, 136, 113, 135]])

In [65]:
np.dot(n1, n2)
n1 @ n2

array([[ 1554, 12627, 13311,  5233],
       [ 2488, 12804, 15365,  3751],
       [ 3429, 17895, 20894,  6168],
       [ 1800, 16057, 17006,  5215]])

In [68]:
# NumPy练习题


SyntaxError: invalid syntax (3324923087.py, line 4)

In [1]:
import numpy as np

In [6]:
# 1、创建一个长度为10的一维全为0的ndarray对象，然后让第五个元素等于1

In [8]:
n = np.zeros(10,dtype=int)
n[4]=1
n

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [19]:
n = np.arange(10,50)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
n[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [22]:
n = np.random.randint(0,100,size=(10,10))
n

array([[ 2, 32, 43, 79, 98, 95, 14, 79, 27, 64],
       [74, 40, 52, 92, 11, 64, 96,  9, 31, 16],
       [89, 89, 82, 73, 68,  2, 12, 23, 60, 62],
       [ 1, 91, 48, 29, 62, 97, 54, 50, 82, 77],
       [20, 77, 37, 59, 76, 91,  5, 69, 18, 62],
       [35, 49, 58, 69, 78,  2, 29, 93, 16, 46],
       [70, 56, 69, 74, 11, 99, 18, 46, 21, 79],
       [29,  7, 64, 85, 49, 45, 40, 18, 83, 57],
       [69, 72,  7,  6, 10,  2, 40, 48, 57,  2],
       [81,  2, 87, 33, 20, 71, 15, 51, 50, 17]])

In [27]:
print(np.argmax(n))
print(np.max(n))

65
99


In [28]:
a = np.argmin(n)
b = np.min(n)
display(a,b)

30

1

In [32]:
n = np.zeros((10,10),dtype=int)
n

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [41]:
n[0]=1
n[9]=1
n[:,0]=1
n[:,-1]=1
n

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [43]:
#优化代码
n[[0,-1]]=1
n[:,[0,-1]]
n

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [69]:
l = [0,1,2,3,4]
n = np.array(l*5).reshape(5,5)
n

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [51]:
n = np.linspace(0,1,12)
n

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [55]:
n = np.random.random(10)
display(n,np.sort(n))

array([0.35735899, 0.02377152, 0.33413333, 0.07202369, 0.85641909,
       0.90925351, 0.68934467, 0.39568044, 0.07437448, 0.81363591])

array([0.02377152, 0.07202369, 0.07437448, 0.33413333, 0.35735899,
       0.39568044, 0.68934467, 0.81363591, 0.85641909, 0.90925351])

In [56]:
n

array([0.35735899, 0.02377152, 0.33413333, 0.07202369, 0.85641909,
       0.90925351, 0.68934467, 0.39568044, 0.07437448, 0.81363591])

In [58]:
n1 = np.sort(n)
n1[-1]=0
n1

array([0.02377152, 0.07202369, 0.07437448, 0.33413333, 0.35735899,
       0.39568044, 0.68934467, 0.81363591, 0.85641909, 0.        ])

In [72]:
n = np.random.randint(0,10,size=10)
n

array([1, 4, 0, 8, 8, 3, 1, 5, 8, 4])

In [73]:
maxn = np.max(n)
maxn

8

In [77]:
max_index = np.argwhere(n==maxn).reshape(-1)
max_index

array([3, 4, 8], dtype=int64)

In [81]:
n[max_index]=0
n

array([1, 4, 0, 0, 0, 3, 1, 5, 0, 4])

In [82]:
n = np.random.randint(0,10,size=(2,3,4,5))
n

array([[[[9, 1, 4, 6, 7],
         [3, 6, 0, 2, 6],
         [6, 1, 9, 5, 1],
         [5, 0, 9, 2, 0]],

        [[8, 4, 8, 7, 5],
         [9, 7, 4, 5, 8],
         [5, 1, 1, 5, 2],
         [4, 2, 9, 2, 7]],

        [[0, 3, 4, 4, 4],
         [3, 3, 1, 1, 8],
         [8, 6, 0, 3, 9],
         [1, 0, 8, 1, 9]]],


       [[[2, 0, 4, 8, 7],
         [2, 9, 4, 2, 7],
         [4, 9, 2, 0, 8],
         [6, 9, 7, 3, 3]],

        [[7, 2, 6, 4, 6],
         [6, 6, 9, 1, 9],
         [7, 7, 8, 8, 1],
         [0, 2, 3, 6, 3]],

        [[1, 9, 1, 4, 6],
         [3, 7, 3, 7, 4],
         [7, 7, 4, 5, 3],
         [3, 8, 7, 6, 1]]]])

In [83]:
sum = n.sum(axis=(2,3))
sum


array([[ 82, 103,  76],
       [ 96, 101,  96]])

In [ ]:
n1 = np.random.randint(0,10,size=(5,3))
n2 = np.random.randint(0,10,size=(3,2))
display(n1,n2,np.dot(n1,n2))

In [92]:
n = np.random.randint(0,10,size=(3,3))
n

array([[8, 5, 2],
       [0, 5, 4],
       [8, 0, 4]])

In [113]:
n2 = np.average(n,axis=1)
n3 = n2.reshape(3,-1)
n3

array([[5.],
       [3.],
       [4.]])

In [ ]:
n-n3